### ISSUE TITLE
Create books application.

### ISSUE THREAD

**Issue by stephane-lucienvauthier** [pytech-fr/calliope#2]
### User story
As the development team, i want to create the books app to start the development.

### Tasks
- [x] Create books app.
- [x] Create routes
- [x] Create index view
- [x] Create book model
